name = "uaqmp-api"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
PORT = 3001
SITE_URL = "https://uaqmp.vercel.app"

# Workers doesn't use Node.js's require() by default
# This setting helps with compatibility
node_compat = true

# No build command to simplify deployment